### ISSUE TITLE
terms gnome is not implemented

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#10]
```text
# smrt hosts
root@kunkka.qam.suse.de      whatever
root@mayweather.qam.suse.de  whatever
```

So there was a discussion about this and the workaround offered for it (for gnome terminal) was the below line:
```text
# gnome-terminal .connected/*(:t)
```
For me this opens a gnome-terminal but not connected to the attached hosts, just my workstation at the path I am already in. This is a bug so far below comes a (kind of) feature request. Should I split the issue into 2?

The different terminal emulators issue can be bypassed by adding a selection (with multiple if's and if else) in the "terms" command that would select the right function (oneliner that opens the right terminal) depending on the terminal emulator the user is using or specifying. I think the 5 most common terminal emulators could work as a beginning.

**Comment by roman-neuhauser** [comment]
which are the 5 most common terminal emulators in your opinion?  and i mean common among the target group for this software.

**Comment by ktsamis** [comment]
gnome-terminal, xterm, maybe konsole ? But you don't have to take all cases, just see which term is already being used to use smrt and choose that one. Also should work with tmux and screen, I guess.

**Comment by roman-neuhauser** [comment]
> just see which term is already being used to use smrt

how would that work?  `$TERM` generally does not equal the name of the binary.

**Comment by ktsamis** [comment]
> how would that work? $TERM generally does not equal the name of the binary

I truly have no idea. How does mtui do it? Maybe a setting in ~/.smrt that specifies your terminal of choice?
