### ISSUE TITLE
man-page smrt-mtui smrt attach minor edit

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#14]
From the manpage:
```text
# man 7 smrt-mtui
smrt attach HOST... -- SYSTEM...
```
But when I try this out with the "--":
```text
# smrt attach root@kunkka.qam.suse.de -- sle-nothing
# smrt hosts
root@kunkka.qam.suse.de      -- sle-nothing
```
It takes the "--" as the product tag. So changing the man-page to 
```text
smrt attach HOST... SYSTEM...
```
would suffice I think.

**Comment by roman-neuhauser** [comment]
since that would mean no reliable (= static) way to distinguish hosts from systems, i've fixed the immediate bug instead: it recognizes the "--" delimiter now.
