### ISSUE TITLE
smrt revert: command not found: parallel

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#15]
```text
# smrt revert
o:22: command not found: parallel
# smrt revert root@kunkka.qam.suse.de
o:22: command not found: parallel
# smrt hosts
root@kunkka.qam.suse.de      -- sle-nothing
```
I have no idea what this means. Is "o" a function? Basically for me what this means is that revert does not work.

**Comment by ktsamis** [comment]
```text
smrt tcf list root@mayweather.qam.suse.de
o:22: command not found: parallel
```
Also appears here.

**Comment by roman-neuhauser** [comment]
thanks, that's a missing `{Build,}Requires: parallel`.  you can fix it for now with `zypper in parallel`.

**Comment by ktsamis** [comment]
Where can I find parallel? I don't have it in any repo and I can't seem to find it.

**Comment by roman-neuhauser** [comment]
sorry, it's gnu_parallel
