### ISSUE TITLE
log.HOST files do not exist (yet?)

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#17]
```text
# man 7 smrt-mtui
     list_history HOST[,...][,EVENT]
          grep EVENT log.HOST
```
But I see no log.* files. Do I need to do something to generate them? Are they generated by some specific command or some event e.g. updating the hosts?

**Comment by roman-neuhauser** [comment]
they spring into existence by using a command which does something on attached hosts such as `smrt-update` or `smrt hosts --packages`.  feel free to reopen if this is not what you meant.
