### ISSUE TITLE
[Feature Request] It would be nice to have the link from bugzilla for this as well

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#6]
```text
smrt xml bugs
bnc988184 timezone:  2016 leap second update
```
Works as expected but it would be nice to have the link and the description as well. There may be another way to get the link I haven't stumbled onto yet.

**Comment by roman-neuhauser** [comment]
use `smrt bugs urls` or just examine the files under `bugs/`.

**Comment by roman-neuhauser** [comment]
sorry it's `smrt bugs` not `smrt bugs urls`.
