### ISSUE TITLE
Man-page needs to include SMRT_CONFIG

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#7]
```text
export SMRT_CONFIG=~/.smrt
```
Otherwise you need to edit /etc/smrt which only root has access to and is read-only for the user. You also need to create the file to have this working of course. It would be nice if we had a file like this automatically created, as well. The man page needs to include the env var so we know how to change it manually as the first step and then we see about creating the file automatically etc.

**Comment by roman-neuhauser** [comment]
pls split off the `~/.smrt` concern into a separate issue, thanks!
