### ISSUE TITLE
[Feature Request] Automatically created ~/.smrt instead of only /etc/smrt

### ISSUE THREAD

**Issue by ktsamis** [openSUSE/smrt#8]
As the summary states it would be nice if we could have ~/.smrt automatically created instead of only /etc/smrt with the right permissions of course. Taken from #7 .

**Comment by lnussel** [comment]
FWIW nowadays use something in ~/.config/

**Comment by ktsamis** [comment]
Same thing really. The filename path is not very important as long as it is documented in the man-pages. Permissions are more important, I think, and to be able to override the values in the "global" config file for whatever value you want.
